import { TemplateSurface } from "./template";
import type { ProjectDetail } from "@/types";

export function AutonomyPilotConciergeSaas454af1Surface({ project }: { project: ProjectDetail }) {
  return (
    <TemplateSurface
      project={project}
      customTitle={"Autonomy Pilot: Concierge SaaS 454AF1"}
      customTagline={"Autonomous pilot: funding, payout, and delivery verified on-chain."}
      customDescription={"This demo surface was generated by the internal DAO git pipeline. It proves that an approved proposal can become a funded project, pay bounties, and publish a user-facing product page through git outbox and git worker without manual edits."}
      ctaLabel={"Open Project Workspace"}
      ctaHref={"/projects/proj_from_proposal_prp_94078a1dabeb1e00"}
    />
  );
}
