// This file is generated by scripts/gen_product_surface_registry.mjs. Do not edit.

import type { ComponentType } from "react";

import type { ProjectDetail } from "@/types";

import { DemoSurface } from "./demo";

export type ProductSurfaceComponent = ComponentType<{ project: ProjectDetail }>;

export const SURFACE_MAP: Record<string, ProductSurfaceComponent> = {
  demo: DemoSurface,
};
