// This file is generated by scripts/gen_product_surface_registry.mjs. Do not edit.

import type { ComponentType } from "react";

import type { ProjectDetail } from "@/types";

import { AutonomyPilotConciergeSaas454af1Surface } from "./autonomy-pilot-concierge-saas-454af1";
import { AutonomyPilotConciergeSaas71d5bfSurface } from "./autonomy-pilot-concierge-saas-71d5bf";
import { DemoSurface } from "./demo";

export type ProductSurfaceComponent = ComponentType<{ project: ProjectDetail }>;

export const SURFACE_MAP: Record<string, ProductSurfaceComponent> = {
  "autonomy-pilot-concierge-saas-454af1": AutonomyPilotConciergeSaas454af1Surface,
  "autonomy-pilot-concierge-saas-71d5bf": AutonomyPilotConciergeSaas71d5bfSurface,
  demo: DemoSurface,
};
