#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

function toPascalCase(slug) {
  return slug
    .split(/[^a-z0-9]+/g)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function main() {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(scriptDir, "..");
  const surfacesDir = path.join(repoRoot, "frontend", "src", "product_surfaces");
  const outFile = path.join(surfacesDir, "registry.gen.ts");

  const entries = fs.readdirSync(surfacesDir, { withFileTypes: true });
  const slugs = entries
    .filter((e) => e.isFile() && e.name.endsWith(".tsx"))
    .map((e) => e.name)
    .filter((name) => !["template.tsx", "index.ts"].includes(name))
    .filter((name) => name !== "registry.gen.ts")
    .map((name) => name.replace(/\.tsx$/, ""))
    .sort((a, b) => a.localeCompare(b));

  const imports = slugs
    .map((slug) => {
      const componentName = `${toPascalCase(slug)}Surface`;
      return `import { ${componentName} } from \"./${slug}\";`;
    })
    .join("\n");

  const mapLines = slugs
    .map((slug) => {
      const componentName = `${toPascalCase(slug)}Surface`;
      const key = /^[a-z][a-z0-9_]*$/.test(slug) ? slug : JSON.stringify(slug);
      return `  ${key}: ${componentName},`;
    })
    .join("\n");

  const source = `// This file is generated by scripts/gen_product_surface_registry.mjs. Do not edit.\n\nimport type { ComponentType } from \"react\";\n\nimport type { ProjectDetail } from \"@/types\";\n\n${imports}\n\nexport type ProductSurfaceComponent = ComponentType<{ project: ProjectDetail }>;\n\nexport const SURFACE_MAP: Record<string, ProductSurfaceComponent> = {\n${mapLines}\n};\n`;

  fs.writeFileSync(outFile, source, "utf8");
  process.stdout.write(
    JSON.stringify(
      { ok: true, out: path.relative(repoRoot, outFile), slugs },
      null,
      0
    )
  );
}

try {
  main();
} catch (err) {
  process.stderr.write(String(err && err.message ? err.message : err) + "\n");
  process.exit(1);
}
